version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile.minimal
    container_name: studio-app-minimal
    restart: unless-stopped
    ports:
      - "9846:9846"
    environment:
      - NODE_ENV=production
      - DATABASE_URL=${DATABASE_URL}
      - NEXTAUTH_URL=${NEXTAUTH_URL}
      - NEXTAUTH_SECRET=${NEXTAUTH_SECRET}
      - AZURE_AD_CLIENT_ID=${AZURE_AD_CLIENT_ID}
      - AZURE_AD_CLIENT_SECRET=${AZURE_AD_CLIENT_SECRET}
      - AZURE_AD_TENANT_ID=${AZURE_AD_TENANT_ID}
      - GOOGLE_API_KEY=${GOOGLE_API_KEY}
      - NEXT_PUBLIC_GOOGLE_FONTS_API_KEY=${NEXT_PUBLIC_GOOGLE_FONTS_API_KEY}
      - DB_HOST=${DB_HOST:-postgres}
      - DB_PORT=${DB_PORT:-5432}
      - REDIS_URL=${REDIS_URL}
      - MINIO_ENDPOINT=${MINIO_ENDPOINT}
      - MINIO_ACCESS_KEY=${MINIO_ACCESS_KEY}
      - MINIO_SECRET_KEY=${MINIO_SECRET_KEY}
      - MINIO_BUCKET_NAME=${MINIO_BUCKET_NAME}
    depends_on:
      - postgres
      - redis
      - minio
    deploy:
      resources:
        limits:
          memory: 1G
          cpus: '0.5'
        reservations:
          memory: 512M
          cpus: '0.25'

  postgres:
    image: postgres:15-alpine
    container_name: studio-postgres-minimal
    restart: unless-stopped
    environment:
      - POSTGRES_DB=${POSTGRES_DB:-studio}
      - POSTGRES_USER=${POSTGRES_USER:-studio}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD:-studio123}
    volumes:
      - postgres_data_minimal:/var/lib/postgresql/data
    ports:
      - "5434:5432"
    deploy:
      resources:
        limits:
          memory: 512M
          cpus: '0.25'
        reservations:
          memory: 256M
          cpus: '0.1'

  redis:
    image: redis:7-alpine
    container_name: studio-redis-minimal
    restart: unless-stopped
    ports:
      - "6381:6379"
    deploy:
      resources:
        limits:
          memory: 256M
          cpus: '0.1'
        reservations:
          memory: 128M
          cpus: '0.05'

  minio:
    image: minio/minio:latest
    container_name: studio-minio-minimal
    restart: unless-stopped
    environment:
      - MINIO_ROOT_USER=${MINIO_ACCESS_KEY:-minioadmin}
      - MINIO_ROOT_PASSWORD=${MINIO_SECRET_KEY:-minioadmin123}
    command: server /data --console-address ":9001"
    volumes:
      - minio_data_minimal:/data
    ports:
      - "9004:9000"
      - "9005:9001"
    deploy:
      resources:
        limits:
          memory: 512M
          cpus: '0.25'
        reservations:
          memory: 256M
          cpus: '0.1'

volumes:
  postgres_data_minimal:
  minio_data_minimal: 