version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        DATABASE_URL: "postgresql://devuser:devpassword@postgres:5432/canditrack_db"
        NEXTAUTH_URL: "${NEXTAUTH_URL}"
        NEXTAUTH_SECRET: "${NEXTAUTH_SECRET}"
        AZURE_AD_CLIENT_ID: "${AZURE_AD_CLIENT_ID}"
        AZURE_AD_CLIENT_SECRET: "${AZURE_AD_CLIENT_SECRET}"
        AZURE_AD_TENANT_ID: "${AZURE_AD_TENANT_ID}"
        GOOGLE_API_KEY: "${GOOGLE_API_KEY}"
        NEXT_PUBLIC_GOOGLE_FONTS_API_KEY: "${NEXT_PUBLIC_GOOGLE_FONTS_API_KEY}"
    ports:
      - "${APP_PORT:-9846}:9846"
    # For production deployments, you typically want the application code to be self-contained
    # within the Docker image. The volume mount `.:/app` is primarily for local development to
    # reflect code changes without rebuilding the image. It's commented out for production-like behavior.
    # If this mount is active in a production-like environment (e.g., Portainer deploying from an image
    # or a CI/CD pipeline), and the host path "." does not contain your application code (including package.json),
    # it will overwrite the files copied into the image, leading to "package.json not found" errors.
    # volumes:
    #   - .:/app # Ensure this is commented out or removed for production deployments where the image is self-contained.
    #
    # The named volumes below are generally fine and can be useful for persisting
    # node_modules and the .next build cache across container restarts, potentially
    # speeding up subsequent starts if the underlying image hasn't changed significantly.
    # volumes:
      # - app_node_modules:/app/node_modules
      # - app_next:/app/.next
    environment:
      DATABASE_URL: ${DATABASE_URL}
      MINIO_ENDPOINT: ${MINIO_ENDPOINT}
      MINIO_PORT: ${MINIO_PORT}
      MINIO_ACCESS_KEY: ${MINIO_ACCESS_KEY}
      MINIO_SECRET_KEY: ${MINIO_SECRET_KEY}
      MINIO_BUCKET_NAME: ${MINIO_BUCKET_NAME}
      MINIO_USE_SSL: ${MINIO_USE_SSL}
      MINIO_PUBLIC_BASE_URL: ${MINIO_PUBLIC_BASE_URL}
      REDIS_URL: ${REDIS_URL}
      NEXTAUTH_URL: ${NEXTAUTH_URL}
      NEXTAUTH_SECRET: ${NEXTAUTH_SECRET}
      # Azure AD Configuration (Optional - set these only if you want to use Azure AD SSO)
      AZURE_AD_CLIENT_ID: ${AZURE_AD_CLIENT_ID}
      AZURE_AD_CLIENT_SECRET: ${AZURE_AD_CLIENT_SECRET}
      AZURE_AD_TENANT_ID: ${AZURE_AD_TENANT_ID}
      # Public Azure AD variables for client-side detection (Optional)
      NEXT_PUBLIC_AZURE_AD_CLIENT_ID: ${NEXT_PUBLIC_AZURE_AD_CLIENT_ID}
      NEXT_PUBLIC_AZURE_AD_TENANT_ID: ${NEXT_PUBLIC_AZURE_AD_TENANT_ID}
      # N8N_RESUME_WEBHOOK_URL: https://ncc-n8n.qsncc.com/webhook/a19157d8-0fdb-44b0-860e-291e52896696
      # N8N_GENERIC_PDF_WEBHOOK_URL: https://ncc-n8n.qsncc.com/webhook/a19157d8-0fdb-44b0-860e-291e52896696
      N8N_RESUME_WEBHOOK_URL: ${N8N_RESUME_WEBHOOK_URL}
      N8N_GENERIC_PDF_WEBHOOK_URL: ${N8N_GENERIC_PDF_WEBHOOK_URL}
      GOOGLE_API_KEY: ${GOOGLE_API_KEY}
      NEXT_PUBLIC_GOOGLE_FONTS_API_KEY: ${NEXT_PUBLIC_GOOGLE_FONTS_API_KEY}
      NODE_ENV: ${NODE_ENV}
      PROCESSOR_API_KEY: ${PROCESSOR_API_KEY}
    depends_on:
      postgres:
        condition: service_healthy
      minio:
        condition: service_healthy
      redis:
        condition: service_healthy
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:9846/api/health" ]
      interval: 60s
      timeout: 15s
      retries: 3
      start_period: 120s
    # The command to run the application is typically defined in the Dockerfile's CMD instruction.
    # For Next.js, this is often `npm run start` (which runs `next start`).
    # You can override it here if needed, but it's usually better to keep it in the Dockerfile.
    command: sh -c "echo 'Starting application...' && sleep 5 && echo 'Running database migrations...' && npx prisma migrate deploy && echo 'Seeding database...' && npx prisma db seed && echo 'Starting Next.js application...' && npm start"

  postgres:
    image: postgres:14-alpine
    ports:
      - "${POSTGRES_PORT:-5432}:5432"
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
      # Ensure proper initialization
      POSTGRES_INITDB_ARGS: "--encoding=UTF-8 --lc-collate=C --lc-ctype=C"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      # Mount the initialization script from root directory
      # PostgreSQL will execute all .sql and .sh files found in /docker-entrypoint-initdb.d/ on first startup
      # when the postgres_data volume is empty or being newly created.
      - ./init-db.sql:/docker-entrypoint-initdb.d/01-init-db.sql:ro
    restart: unless-stopped
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB}"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 30s

  minio:
    image: minio/minio:latest
    ports:
      - "${MINIO_API_PORT:-9847}:9000" # MinIO API port
      - "${MINIO_CONSOLE_PORT:-9848}:9001" # MinIO Console port
    environment:
      MINIO_ROOT_USER: ${MINIO_ROOT_USER}
      MINIO_ROOT_PASSWORD: ${MINIO_ROOT_PASSWORD}
      MINIO_SERVER_URL: http://localhost:9000
      MINIO_BROWSER_REDIRECT_URL: http://localhost:${MINIO_CONSOLE_PORT}
    command: server /data --console-address ":9001" --address ":9000"
    volumes:
      - minio_data:/data
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:9000/minio/health/live"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 30s

  redis:
    image: redis:alpine
    ports:
      - "${REDIS_EXTERNAL_PORT:-9849}:6379"
    volumes:
      - redis_data:/data
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 30s

  upload-queue-processor:
    build:
      context: .
      dockerfile: Dockerfile
    command: sh -c "until nc -z postgres ${POSTGRES_PORT}; do echo Waiting for Postgres...; sleep 2; done; until nc -z minio ${MINIO_PORT}; do echo Waiting for MinIO...; sleep 2; done; until nc -z redis ${REDIS_PORT}; do echo Waiting for Redis...; sleep 2; done; node process-upload-queue.mjs"
    environment:
      DATABASE_URL: ${DATABASE_URL}
      MINIO_ENDPOINT: ${MINIO_ENDPOINT}
      MINIO_PORT: ${MINIO_PORT}
      MINIO_ACCESS_KEY: ${MINIO_ACCESS_KEY}
      MINIO_SECRET_KEY: ${MINIO_SECRET_KEY}
      MINIO_BUCKET_NAME: ${MINIO_BUCKET_NAME}
      MINIO_USE_SSL: ${MINIO_USE_SSL}
      MINIO_PUBLIC_BASE_URL: ${MINIO_PUBLIC_BASE_URL}
      REDIS_URL: ${REDIS_URL}
      NEXTAUTH_URL: ${NEXTAUTH_URL}
      NEXTAUTH_SECRET: ${NEXTAUTH_SECRET}
      AZURE_AD_CLIENT_ID: ${AZURE_AD_CLIENT_ID}
      AZURE_AD_CLIENT_SECRET: ${AZURE_AD_CLIENT_SECRET}
      AZURE_AD_TENANT_ID: ${AZURE_AD_TENANT_ID}
      NEXT_PUBLIC_AZURE_AD_CLIENT_ID: ${NEXT_PUBLIC_AZURE_AD_CLIENT_ID}
      NEXT_PUBLIC_AZURE_AD_TENANT_ID: ${NEXT_PUBLIC_AZURE_AD_TENANT_ID}
      N8N_RESUME_WEBHOOK_URL: ${N8N_RESUME_WEBHOOK_URL}
      N8N_GENERIC_PDF_WEBHOOK_URL: ${N8N_GENERIC_PDF_WEBHOOK_URL}
      GOOGLE_API_KEY: ${GOOGLE_API_KEY}
      NEXT_PUBLIC_GOOGLE_FONTS_API_KEY: ${NEXT_PUBLIC_GOOGLE_FONTS_API_KEY}
      NODE_ENV: ${NODE_ENV}
      PROCESSOR_INTERVAL_MS: ${PROCESSOR_INTERVAL_MS}
      PROCESSOR_URL: ${PROCESSOR_URL}
      PROCESSOR_API_KEY: ${PROCESSOR_API_KEY}
    depends_on:
      app:
        condition: service_healthy
      postgres:
        condition: service_healthy
      minio:
        condition: service_healthy
      redis:
        condition: service_healthy
    restart: unless-stopped

  ws-queue-bridge:
    build:
      context: .
      dockerfile: Dockerfile
    command: sh -c "until nc -z redis ${REDIS_PORT}; do echo Waiting for Redis...; sleep 2; done; node ws-queue-bridge.js"
    environment:
      REDIS_URL: ${REDIS_URL}
      WS_QUEUE_BRIDGE_PORT: ${WS_QUEUE_BRIDGE_PORT:-3002}
      WS_ALLOWED_ORIGINS: ${WS_ALLOWED_ORIGINS}
      NODE_ENV: ${NODE_ENV}
    ports:
      - "${WS_QUEUE_BRIDGE_PORT:-3002}:3002"
    depends_on:
      redis:
        condition: service_healthy
    restart: unless-stopped

volumes:
  postgres_data:
  minio_data:
  redis_data:
  # app_node_modules:
  # app_next:
