-- This file is no longer used directly by docker-compose.yml.
-- The database initialization script has been moved to 'pg-init-scripts/init-db.sql'.
-- Please create a directory named 'pg-init-scripts' in your project root
-- and move (or copy) the content of the original init-db.sql into
-- 'pg-init-scripts/init-db.sql'.
-- The docker-compose.yml file now mounts the entire 'pg-init-scripts' directory.
