@echo off
echo Stopping upload queue processor service...
docker-compose stop upload-queue-processor

echo Removing upload queue processor container...
docker-compose rm -f upload-queue-processor

echo Starting upload queue processor service...
docker-compose up -d upload-queue-processor

echo Checking logs...
docker-compose logs -f upload-queue-processor 